# Generated by Django 3.0.2 on 2020-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='huangse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=60, verbose_name='序列号')),
                ('desc', models.URLField(max_length=1200, verbose_name='详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='souci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titstr', models.CharField(max_length=200, verbose_name='搜索关键词')),
            ],
        ),
    ]
