# Generated by Django 3.0.2 on 2020-01-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='huangse',
            new_name='gep',
        ),
    ]
