# Generated by Django 3.0.2 on 2020-02-28 19:29

from django.db import migrations
import gep_search.models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0002_auto_20200107_1608'),
    ]

    operations = [

    ]
