# Generated by Django 3.0.2 on 2020-02-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0003_gep_vec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='souci',
        ),
        migrations.RemoveField(
            model_name='gep',
            name='series_id',
        ),
        migrations.AddField(
            model_name='gep',
            name='col_name',
            field=models.CharField(default='', max_length=50, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='gep',
            name='file_name',
            field=models.CharField(default='', max_length=100, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='gep',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
