# Generated by Django 3.0.2 on 2020-02-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0004_auto_20200229_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gep',
            name='id',
            field=models.IntegerField(max_length=60, primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
