# Generated by Django 3.0.2 on 2020-02-29 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0005_auto_20200229_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='gep',
            name='vec',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0, size=None),
        ),
        migrations.AlterField(
            model_name='gep',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
