# Generated by Django 3.0.2 on 2020-02-29 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0006_auto_20200229_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gep',
            name='vec',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None),
        ),
    ]
