# Generated by Django 3.0.2 on 2020-02-29 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0008_auto_20200229_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gep',
            name='desc',
            field=models.CharField(default='', max_length=1200, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='gep',
            name='vec',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
