# Generated by Django 3.0.2 on 2020-02-29 12:09

from django.db import migrations
import gep_search.models


class Migration(migrations.Migration):

    dependencies = [
        ('gep_search', '0009_auto_20200229_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gep',
            name='vec',
            field=gep_search.models.ListField(),
        ),
    ]
